export const TWEET_SEARCH_STARTED = "TWEET_SEARCH_STARTED";
export const TWEET_SEARCH_LOADED = "TWEET_SEARCH_LOADED";
export const TWEET_SEARCH_ERROR = "TWEET_SEARCH_ERROR";
export const TWEET_DETAILS_REQUESTED = "TWEET_DETAILS_REQUESTED"
export const TWEET_DETAILS_LOADED = "TWEET_DETAILS_LOADED"